[package]
name = "data-postprocessor"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
plotters = "0.3.1"
rand = { version = "0.8.5", features = ["small_rng"] }
